name: bebasid Automator Domain Scanner
on:
  push:
    branches:
      - main
jobs:
  scan_domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip wget
          curl -LO https://github.com/findomain/findomain/releases/latest/download/findomain-linux.zip
          unzip findomain-linux.zip
          chmod +x findomain
          sudo mv findomain /usr/bin/findomain
          wget https://raw.githubusercontent.com/bebasid/bebasid/master/dev/scripts/scan.py
          echo "INSTALLATION DONE - ALL SET"
      - name: Run Findomain
        run: |
          findomain -f domainlist -r -u subdomainlist
      - name: Sort Subdomains
        run: |
          python - <<EOF
          with open("subdomainlist", "r") as file:
              lines = file.readlines()
          domain_dict = {}
          for line in lines:
              subdomain = line.strip()
              domain = subdomain.split(".")[-2] + "." + subdomain.split(".")[-1]
              if domain not in domain_dict:
                  domain_dict[domain] = []
              domain_dict[domain].append(subdomain)
          for domain in domain_dict:
              domain_dict[domain].sort(key=len)
          sorted_subdomains = []
          for domain in sorted(domain_dict.keys()):
              sorted_subdomains.extend(domain_dict[domain])
          with open("subdomainlist_sorted", "w") as file:
              file.write("\n".join(sorted_subdomains))
          EOF
      - name: Run Scan
        run: |
          python scan.py subdomainlist_sorted
          echo
          echo "Result Lists:"
          cat hosts-subdomainlist_sorted
      - name: Release hosts
        run: |
          mv hosts-subdomainlist_sorted hosts
      - name: Add BEBASID Text to Hosts File
        run: |
          sudo cat > temp_hosts <<EOF
          # BEBASID - Peduli Internet Netral
          # Situs resmi kami: https://bebasid.com/
          # Hosts ditulis oleh Komunitas Internet Netral Indonesia
          # Dengan mengunduh BEBASID dan menggunakan aplikasi ini berarti menerima dan setuju untuk terikat dan mematuhi ketentuan yang berada di dalam halaman berikut: https://github.com/bebasid/bebasid/blob/master/dev/readme/RULES.md

          # [PEMBERITAHUAN SEBELUM MENGGUNAKAN HOSTS]
          # Untuk Wi-Fi / Provider (ISP) yang memakai Inspeksi Paket Dalam (DPI), harap gunakan BebasIT / BebasID IT sebelum menggunakan hosts kami
          EOF
          sudo cat hosts >> temp_hosts
          sudo mv temp_hosts hosts

      - name: Commit changes
        run: |
          git config --global user.email "gvoze32@yahoo.com"
          git config --global user.name "zksbot"
          git add hosts
          git commit -m "Compile hosts"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.UPDATE_TOKEN }}
